package SearchButtonItems;

import Mainpackage.*;
import MenuItems.*;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

class StaffModel{
    private int staff_id, staff_age ,region_no  ;
    private String staff_name, staff_phone, staff_gender,staff_address,staff_designation ,staff_hiredate;

    public StaffModel(int staff_id, int staff_age, int region_no, String staff_name, String staff_phone, String staff_gender, String staff_address, String staff_designation, String staff_hiredate) {
        this.staff_id = staff_id;
        this.staff_age = staff_age;
        this.region_no = region_no;
        this.staff_name = staff_name;
        this.staff_phone = staff_phone;
        this.staff_gender = staff_gender;
        this.staff_address = staff_address;
        this.staff_designation = staff_designation;
        this.staff_hiredate = staff_hiredate;
    }

    public int getStaff_id() {
        return staff_id;
    }

    public int getStaff_age() {
        return staff_age;
    }

    public int getRegion_no() {
        return region_no;
    }

    public String getStaff_name() {
        return staff_name;
    }

    public String getStaff_phone() {
        return staff_phone;
    }

    public String getStaff_gender() {
        return staff_gender;
    }

    public String getStaff_address() {
        return staff_address;
    }

    public String getStaff_designation() {
        return staff_designation;
    }

    public String getStaff_hiredate() {
        return staff_hiredate;
    }
    
    
}

public class searchStaffInfoPanel extends javax.swing.JFrame {
   //variable declaration of query so that we can use it while passing into a method
    //query string is used in some method in this name: "qString". queryString must be static
    private static String queryString;

    public void setQueryString(String qString) {
        this.queryString = qString;
    }

    //Array List for retrieving info from database
    //qString is the String of Query operation
    private ArrayList<StaffModel> staffList(String qString) {
        ArrayList<StaffModel> staffrsList = new ArrayList<>();
        DatabaseConnection dbc = new DatabaseConnection();
        try {
            ResultSet rs = dbc.resultSetQuery(qString);

            StaffModel staff;
            while (rs.next()) {
                staff = new StaffModel(rs.getInt("staff_id"),
                        rs.getInt("staff_age"),
                        rs.getInt("region_no"),
                        rs.getString("staff_name"),
                        rs.getString("staff_phone"),
                        rs.getString("staff_gender"),
                        rs.getString("staff_hiredate"),
                        rs.getString("staff_address"),
                        rs.getString("staff_designation")    
                );
                staffrsList.add(staff);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        }

        //closing database
        dbc.dbClose();

        return staffrsList;
    }

    //showing values from database to the jtable
    //qString is the String of Query operation
    private void showSearchedstaffrInfo(String qString) {
        ArrayList<StaffModel> list = staffList(qString);
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        Object[] row = new Object[12];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getStaff_id();
            row[1] = list.get(i).getStaff_name();
            row[2] = list.get(i).getStaff_phone();
            row[3] = list.get(i).getStaff_gender();
            row[4] = list.get(i).getStaff_address();
            row[5] = list.get(i).getStaff_designation();
            row[6] = list.get(i).getStaff_hiredate();
            row[7] = list.get(i).getRegion_no();
            row[8] = list.get(i).getStaff_age();

            model.addRow(row);
        }
    }

    /**
     * Creates new form searchVisitorInfoPanel
     */
    public searchStaffInfoPanel(String queryString) {
        initComponents();
        //setting the screen in the middle of the screen
        setLocationRelativeTo(null);

        //shwoing the jtable with values
        showSearchedstaffrInfo(queryString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tableScrollPanel = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Staff's Information");
        setMaximumSize(new java.awt.Dimension(530, 450));
        setMinimumSize(new java.awt.Dimension(530, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(530, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        contentPanel.setMaximumSize(new java.awt.Dimension(654, 471));
        contentPanel.setMinimumSize(new java.awt.Dimension(654, 471));
        contentPanel.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Search Result");
        contentPanel.add(jLabel2);
        jLabel2.setBounds(10, 30, 510, 30);

        jPanel1.setBackground(new java.awt.Color(65, 40, 107));
        jPanel1.setLayout(null);
        contentPanel.add(jPanel1);
        jPanel1.setBounds(10, 10, 510, 10);

        jPanel2.setBackground(new java.awt.Color(65, 40, 107));
        jPanel2.setLayout(null);
        contentPanel.add(jPanel2);
        jPanel2.setBounds(10, 70, 510, 10);

        jPanel3.setBackground(new java.awt.Color(65, 40, 107));
        jPanel3.setLayout(null);
        contentPanel.add(jPanel3);
        jPanel3.setBounds(370, 30, 150, 30);

        jPanel4.setBackground(new java.awt.Color(65, 40, 107));
        jPanel4.setLayout(null);
        contentPanel.add(jPanel4);
        jPanel4.setBounds(10, 30, 150, 30);

        tableScrollPanel.setBackground(new java.awt.Color(255, 255, 255));
        tableScrollPanel.setForeground(new java.awt.Color(255, 255, 255));

        dataTable.setBackground(new java.awt.Color(255, 255, 255));
        dataTable.setForeground(new java.awt.Color(0, 0, 0));
        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Phone", "Sex", "Age", "Address", "Designation", "Hire Date", "Region"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableScrollPanel.setViewportView(dataTable);

        contentPanel.add(tableScrollPanel);
        tableScrollPanel.setBounds(10, 90, 510, 300);

        getContentPane().add(contentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchStaffInfoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchStaffInfoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchStaffInfoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchStaffInfoPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchStaffInfoPanel(queryString).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane tableScrollPanel;
    // End of variables declaration//GEN-END:variables
}
